### ISSUE TITLE
api-dev is returning bad user information

### ISSUE THREAD

**Issue by nmaytan** [NSLS2/nsls2api#34]
This is causing failures for several proposals. Tested only against 2024-1 cycle so far. Some examples of errors are:
`None`, `lsdc-dmx`, `n2sn-dataadmin-sst1` (should be sst), I think that's most/all I've seen, but I may have missed others as I didn't run against all proposals..

```
Error while processing proposal 313306.
Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 835, in write_posix_acls
    acl = posix1e.ACL(text=",".join(acl_entries))
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 455, in main
    process_proposal(
  File "/tmp/test-proposals/create_proposal_directories.py", line 203, in process_proposal
    update_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 889, in update_acls
    write_posix_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 838, in write_posix_acls
    raise RuntimeError(
RuntimeError:
ACL object creation failed (POSIX). Details:

u::rwx,u:nsls2data:rwx,u:None:rwx,u:None:rwx,g::rwx,g:n2sn-right-dataadmin:rwx,g:n2sn-right-dataadmin-tes:rwx,o::---

Error while processing proposal 313683.
Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 835, in write_posix_acls
    acl = posix1e.ACL(text=",".join(acl_entries))
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 455, in main
    process_proposal(
  File "/tmp/test-proposals/create_proposal_directories.py", line 256, in process_proposal
    update_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 889, in update_acls
    write_posix_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 838, in write_posix_acls
    raise RuntimeError(
RuntimeError:
ACL object creation failed (POSIX). Details:

u:softioc-sst1:rwx,u:softioc:rwx,u:bluesky-sst1:rwx,u:workflow-sst1:r-x,u::r-x,u:nsls2data:r-x,g:n2sn-dataadmin-sst1:r-x,g:n2sn-dataadmin:r-x,g::r-x,o::---

Error while processing proposal 314563.
Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 835, in write_posix_acls
    acl = posix1e.ACL(text=",".join(acl_entries))
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 455, in main
    process_proposal(
  File "/tmp/test-proposals/create_proposal_directories.py", line 203, in process_proposal
    update_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 889, in update_acls
    write_posix_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 838, in write_posix_acls
    raise RuntimeError(
RuntimeError:
ACL object creation failed (POSIX). Details:

u::rwx,u:nsls2data:rwx,u:None:rwx,u:None:rwx,g::rwx,g:n2sn-right-dataadmin:rwx,g:n2sn-right-dataadmin-fis:rwx,o::---

Error while processing proposal 311875.
Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 835, in write_posix_acls
    acl = posix1e.ACL(text=",".join(acl_entries))
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test-proposals/create_proposal_directories.py", line 455, in main
    process_proposal(
  File "/tmp/test-proposals/create_proposal_directories.py", line 203, in process_proposal
    update_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 889, in update_acls
    write_posix_acls(
  File "/tmp/test-proposals/create_proposal_directories.py", line 838, in write_posix_acls
    raise RuntimeError(
RuntimeError:
ACL object creation failed (POSIX). Details:

u::rwx,u:nsls2data:rwx,u:workflow-fmx:rwx,u:softioc-fmx:rwx,u:lsdc-dmx:rwx,g::rwx,g:n2sn-right-dataadmin:rwx,g:n2sn-right-dataadmin-fmx:rwx,o::---

Failed proposals:
313306
313683
314563
311875
Proposals successfully handled: 6
```

**Comment by nmaytan** [comment]
@stuartcampbell for visibility

**Comment by stuartcampbell** [comment]
`lsdc-dmx` was just a typo in the database
